### PR TITLE
chore: retry flaky tests

### PR DESCRIPTION
**Pull request by wa0x6e**
Retry flaky tests, which are failing sporadically because of timeout

### CODE REVIEW

**Comment by Todmy** [comment]
tests fail locally. What version of node do you use?

**Comment by wa0x6e** [comment]
> tests fail locally. What version of node do you use?

16

**Comment by wa0x6e** [comment]
What’s the error? Timeout?

**Comment by wa0x6e** [comment]
The code is not working on node 18, due to some dependencies not supporting it

**Comment by Todmy** [comment]
> What’s the error? Timeout?

Screenshot 2023-10-02 at 16 03 03

Screenshot 2023-10-02 at 16 04 34

**Comment by wa0x6e** [comment]
> > What’s the error? Timeout?
> 
> Screenshot 2023-10-02 at 16 03 03 Screenshot 2023-10-02 at 16 04 34

Did you set the aws keys?

**Comment by Todmy** [comment]
where can I find them?

**Review by Todmy — APPROVED** [review]
utACK

**Pull request merged**
